import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Platypi } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
});

const platypi = Platypi({
  subsets: ["latin"],
  variable: "--font-platypi",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${platypi.variable} antialiased bg-[#FEF6EE]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
